### ISSUE TITLE
Allow `base = 4.15`?

### ISSUE THREAD

**Issue by kindaro** [Lysxia/show-combinators#6]
This package does not work with new GHC. I think this is because the version bound on `base` is too low. See for example:

    % cabal run
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    [__0] trying: fake-package-0 (user goal)
    [__1] trying: generic-data-0.9.2.0 (dependency of fake-package)
    [__2] trying: show-combinators-0.2.0.0 (dependency of generic-data)
    [__3] next goal: base (dependency of fake-package)
    [__3] rejecting: base-4.15.0.0/installed-4.15.0.0 (conflict: show-combinators
    => base>=4.8 && <4.15)
    [__3] rejecting: base-4.14.1.0, base-4.14.0.0, base-4.13.0.0, base-4.12.0.0,
    base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0,
    base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2,
    base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0,
    base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0,
    base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0,
    base-3.0.3.2, base-3.0.3.1 (constraint from project config TODO requires
    ==4.15.0.0)
    [__3] fail (backjumping, conflict set: base, fake-package, show-combinators)
    After searching the rest of the dependency tree exhaustively, these were the
    goals I've had most trouble fulfilling: base, show-combinators, generic-data,
    fake-package

I have a local copy where I raised the upper bound on `base` a notch and it works fine.

**Comment by Lysxia** [comment]
Thanks, I made a revision for 0.2.0.0 bumping the upper bound to `base < 5`.

**Comment by kindaro** [comment]
Awesome!
